# Manually started action to build Picotool/OpenOCD for Windows and upload to an artifact

name: Build All Windows
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install cross compilation tools
      run: |
           apt-get install -y gcc g++ make git gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu zip gcc-i686-linux-gnu g++-i686-linux-gnu

    - name: Build mklittlefs x86-64
      run: |
        tgt=linux pfx=x86_64-linux-gnu exe="" AHOST="x86_64-pc-linux-gnu" TARGET_OS=${tgt} CC=${pfx}-gcc CXX=${pfx}-g++ STRIP=${pfx}-strip make clean mklittlefs${exe} BUILD_CONFIG_NAME="-arduino" CPPFLAGS=""
        name=mklittlefs-$(git rev-parse --short HEAD)
        mkdir -p tmp/mklittlefs
        mv mklittlefs tmp/mklittlefs/.
        cd tmp
        zip -rq ../x86_64-linux-gnu-${name}.zip mklittlefs
        cd ..
        rm -rf tmp
        make clean
    - name: Build mklittlefs aarch64
      run: |
        tgt=linux pfx=aarch64-linux-gnu exe="" AHOST="aarch64-linux-gnu" TARGET_OS=${tgt} CC=${pfx}-gcc CXX=${pfx}-g++ STRIP=${pfx}-strip make clean mklittlefs${exe} BUILD_CONFIG_NAME="-arduino" CPPFLAGS=""
        name=mklittlefs-$(git rev-parse --short HEAD)
        mkdir -p tmp/mklittlefs
        mv mklittlefs tmp/mklittlefs/.
        cd tmp
        zip -rq ../aarch64-linux-gnu-${name}.zip mklittlefs
        cd ..
        rm -rf tmp
        make clean
    - name: Build mklittlefs arm
      run: |
        tgt=linux pfx=arm-linux-gnueabihf exe="" AHOST="arm-linux-gnueabihf" TARGET_OS=${tgt} CC=${pfx}-gcc CXX=${pfx}-g++ STRIP=${pfx}-strip make clean mklittlefs${exe} BUILD_CONFIG_NAME="-arduino" CPPFLAGS=""
        name=mklittlefs-$(git rev-parse --short HEAD)
        mkdir -p tmp/mklittlefs
        mv mklittlefs tmp/mklittlefs/.
        cd tmp
        zip -rq ../arm-linux-gnueabihf-${name}.zip mklittlefs
        cd ..
        rm -rf tmp
        make clean

    - name: Upload mklittlefs x86-64
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-linux-gnu-mklittlefs.zip
        path: x86_64-linux-gnu-mklittlefs-*.zip
    - name: Upload mklittlefs aarch64
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-linux-gnu-mklittlefs.zip
        path: aarch64-linux-gnu-mklittlefs-*.zip
    - name: Upload mklittlefs arm-linux-gnueabihf
      uses: actions/upload-artifact@v4
      with:
        name: arm-linux-gnueabihf-mklittlefs.zip
        path: arm-linux-gnueabihf-mklittlefs-*.zip

