name: Build MacOS ARM
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build mklittlefs MacARM
      run: |
        rm -f *.json *.gz *.zip
        pfx=aarch64-apple-darwin20
        AHOST=aarch64-apple-darwin TARGET_OS=osx CC=gcc CXX=g++ STRIP=strip make clean mklittlefs BUILD_CONFIG_NAME="-arduino" CPPFLAGS=""
    - name: Package mklittlefs MacARM
      run: |
        name=mklittlefs-$(git rev-parse --short HEAD)
        mkdir -p tmp/mklittlefs
        mv mklittlefs tmp/mklittlefs/.
        cd tmp
        zip -rq ../aarch64-apple-darwin-${name}.zip mklittlefs
        cd ..
        rm -rf tmp
    - name: Upload mklittlefs MacARM
      uses: actions/upload-artifact@v4
      with:
        name: aarch64-apple-darwin-mklittlefs.zip
        path: aarch64-apple-darwin-mklittlefs-*.zip
